# Generated by Django 6.0.4 on 2026-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_category_job_skill_category'),
        ('users', '0004_freelancerprofile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skill_category',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='users.skillcategory'),
        ),
    ]
