services:
  - type: web
    name: dealancer-backend
    env: docker
    plan: free
    dockerContext: ./Backend
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dealancer-db
          property: connectionString
      - key: DEBUG
        value: "True"

  - type: web
    name: dealancer-frontend
    env: docker
    plan: free
    dockerContext: ./Frontend
    dockerfilePath: ./Frontend/Dockerfile
    envVars:
      - key: VITE_BACKEND_URL
        value: "https://dealancer-backend.onrender.com/api"

databases:
  - name: dealancer-db
    plan: free
    postgresMajorVersion: 15
