services:
  - type: web
    name: dealancer-backend
    env: docker
    plan: free
    dockerContext: ./Backend
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dealancer-db
          property: connectionString
      - key: DEBUG
        value: "False"

  - type: web
    name: dealancer-frontend
    env: docker
    plan: free
    dockerContext: ./Frontend
    dockerfilePath: ./Frontend/Dockerfile
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: dealancer-backend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: dealancer-db
    plan: free
    postgresMajorVersion: 15
