# Generated by Django 6.0.4 on 2026-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_skillcategory_clientprofile_freelancerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='users.skillcategory'),
        ),
    ]
